CMakeLists.txt
README.md
src/chain/merkle_tree.cpp
src/chain/merkle_tree.hpp
tests/chain/CMakeLists.txt
tests/chain/test.cpp

- Transactions 을 저장할때 머클트리가 필요하다
- 머클트리 자료구조 추가(MerkleTree 클래스)

# ADD - Merkle Tree 추가

---

src/utils/hmac_key_maker.hpp

- hmac_key_maker에서 잘못된 변수명을 변경함

# EDIT - 일부 잘못된 변수명 수정

---

.gitignore
src/modules/storage/block_json.hpp
src/modules/storage/storage.cpp
src/modules/storage/storage.hpp
tests/modules/CMakeLists.txt
tests/modules/test.cpp

- Block, Block Hash, Block Meta, Transaction, Certificate의 저장 / 검색
- 각각에 대한 Test Case를 생성

# ADD - LevelDB 저장 / 검색

---

src/chain/merkle_tree.cpp
src/services/transaction_fetcher.cpp
src/utils/sha256.hpp
tests/chain/test.cpp
tests/utils/test.cpp

- encrypt -> hash 로 함수명 변경
- hex_encode -> base64_encode 로 변경

# EDIT - Sha256::encrypt -> Sha256::hash

---

src/modules/storage/block_json.hpp
src/modules/storage/storage.cpp
tests/modules/test.cpp

- Cert 저장 / 검색
- Block Header Hash 저장 / 검색
- 블록헤더에 Transaction List 추가

# ADD - LevelDB (Cert, Block Header Hash) 저장 / 검색

---

src/chain/merkle_tree.cpp
src/chain/merkle_tree.hpp
src/chain/transaction.hpp
src/chain/types.hpp
src/modules/communication/grpc_util.cpp
src/services/block_generator.cpp
src/services/message_factory.hpp
src/services/message_fetcher.hpp
src/services/signature_requester.cpp
src/services/transaction_fetcher.cpp
src/utils/sha256.hpp
tests/chain/test.cpp
tests/modules/CMakeLists.txt
tests/modules/test.cpp
tests/services/test.cpp
tests/utils/test.cpp

- 내부적으로는 uint8_t 로 데이터를 처리해야하는데 string으로 처리하고 있었음
- vector<uint8_t> 타입으로 변경
- 일부 임시처리한 코드 TODO 주석 붙임

# EDIT - sha256(string) -> sha256(vector<uint8_t>)로 변경

---

main.cpp
src/application.cpp
src/application.hpp
src/chain/merkle_tree.cpp
src/chain/merkle_tree.hpp
src/chain/types.hpp
src/modules/communication/communication.cpp
src/modules/communication/communication.hpp
src/modules/communication/grpc_merger.cpp
src/modules/communication/grpc_merger.hpp
src/modules/communication/grpc_util.cpp
src/modules/communication/grpc_util.hpp
src/modules/storage/storage.cpp
src/services/block_generator.cpp
src/services/message_factory.hpp
src/services/signature_requester.hpp
src/services/transaction_fetcher.cpp
src/utils/hmac_key_maker.hpp
src/utils/sha256.hpp

- Communication 모듈이 완성됨에 따라 application이 실행할때 모듈이 실행되도록 수정
- thread_group(vector)를 추가하고 3개의 thread가 동작하도록 함
- clang-format 형식에 안맞추어진 부분이 있어서 같이 수정

# EDIT - Application 시작할때 통신모듈 실행시키도록 수정

---

src/services/signature_requester.cpp
src/services/signer_pool.cpp
src/services/signer_pool.hpp
src/services/signer_pool_manager.cpp
src/services/signer_pool_manager.hpp
src/services/transaction_fetcher.hpp
tests/services/test.cpp

- SignerPool을 하나의 class로 분리해달라는 요청에 따라 클래스 생성 후 분리
- Signer 데이터를 넣거나 가져오는 일들을 모두 SignerPool 에게 delegate하도록 수정

REFACTOR - SignerPool class 로 분리

---

src/utils/random_number_generator.hpp
tests/utils/test.cpp

- 랜덤 Number를 Generate하는 클래스(유틸) 추가
- 사이즈를 입력으로 받아서 그 사이즈만큼 데이터를 생성함

# ADD - Random Number Generator

---

src/chain/static_merkle_tree.hpp

- 리프 노드의 크기는 알아서 바꿉니다. 거기  const로 선언해 놨어요.

ADD 정적 머클트리를 만들어주는 클래스를 추가했습니다.

---

src/utils/template_singleton.hpp

좀 올려주세요. 불편하단 말이에요. (by jeonil)

 #ADD - template singleton

---

src/utils/compressor.hpp
tests/utils/test.cpp

- LZ4 compression / decompression 에서 원본의 크기를 몰라도 압축을 풀 수 있도록 수정 하였습니다.
- 변수 캐스팅 하는 부분을 수정하였습니다.

#FIX - compressor 수정

---

src/modules/communication/grpc_util.cpp
src/modules/communication/grpc_util.hpp
src/utils/hmac.hpp
tests/modules/test.cpp
tests/utils/test.cpp

- hmac 검증 test 코드 작성
- grpc_util 의 getJsonSize 함수 버그 수정
* 전에 바이트 파싱할 때, 반대로 파싱하여 문제가 생겼던 것 수정

 #ADD - hmac 검증 및 생성 추가

---

src/services/input_queue.hpp
src/services/output_queue.hpp

현재 사용 중인 input queue, output queue를 나중에 이를 이용하여 수정

 #ADD - input queue, output queue

---

CMakeLists.txt
src/modules/storage/block_json.hpp
src/modules/storage/storage.cpp
src/modules/storage/storage.hpp
tests/modules/CMakeLists.txt
tests/modules/test.cpp

Storage Class를 재작성
- GE7. Storage
- GE11. Block Query

Storage Class의 재작성, Test JSON 재작성, CMake Filesystem 추가

---

src/services/signer_pool_manager.cpp
src/services/signer_pool_manager.hpp
src/utils/hmac_key_maker.hpp
tests/utils/test.cpp

Reverts gruut/enterprise-merger#44
제가 실수했어요.
message-response-2에 이미 이 코드가 들어있더군요.

Revert "# ADD - Merger DH 키 계산하는 코드 추가"

---

src/chain/signer_pool.hpp
src/modules/communication/grpc_merger.cpp
src/modules/communication/grpc_util.cpp
src/modules/communication/grpc_util.hpp
src/modules/storage/block_json.hpp
src/modules/storage/storage.cpp
src/modules/storage/storage.hpp
src/services/input_queue.hpp
src/services/output_queue.hpp
src/utils/hmac.hpp
src/utils/template_singleton.hpp

- 많은 분들이 clang-format 적용하는 걸 까먹습니다.
- 슬랙에 공유해 둔 c++ 개발자들에게 드리는 편지를 읽고 적용해주세요.

" # FIX - clang-format /all"

---

src/services/signer_pool_manager.cpp
tests/utils/test.cpp

- 기획서에 명시된대로 64바이트에서 32바이트로 수정함
[ref](https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/49250343/GE5.+Data+Structure)
[task](https://thevaulters.atlassian.net/browse/GEN-97)

# EDIT - merger_nonce를 64바이트에서 32바이트로 수정

---

src/modules/communication/grpc_util.cpp
tests/utils/test.cpp

- 현재 Signer 쪽에서 main_verison 정보가 넘어오는데 (값 1), little endian 형식으로 넘어와서 0x10으로 파싱됨.
- 헤더 파싱에 대한 정확한 코드 구현이 완료되면 주석해제할 예정

# EDIT - Main version checking 비활성화

---

src/modules/communication/msg_schema.hpp

- 설계문서 오류 
- content type :string -> array

 # FIX - json-schema MSG_TX 수정

---

src/services/signer_pool_manager.hpp

- signer_pool을 Application에서 관리하고 있으므로, 더 이상 SignerPoolManager 에서 필요가 없다. 그래서 m_signer_pool 멤버변수 제거

# EDIT - SignerPoolManager 사소한 수정

---

main.cpp
src/modules/transaction_collector/transaction_collector.hpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp

- 종전의 코드에서는 `TransactionCollector` 가 `Module`을 상속받고 있어서, 트랜잭션 메시지의 유무와 상관없이 main.cpp 에서 독립적으로 실행된다.
- MSG_TX를 수신했을때 TransactionCollector의 타이머가 실행되도록 하기 위해서 더 이상 Module을 상속받지 않도록 수정

# EDIT - TransactionCollector가 독립적으로 실행되지 않도록 수정

---

src/utils/compressor.hpp

- 함수 추가 및 캐스팅 수정
* uint8_t vector를 받는 함수 추가

 # EDIT - Compressor 함수 추가 및 수정

---

src/modules/storage/block_json.hpp
src/modules/storage/storage.cpp
src/modules/storage/storage.hpp
tests/modules/test.cpp

- saveBlock시에 mPos, mtree를 적용
- Transaction id가 주어지면 해당하는 시블링들을 검색(return vector<string>)

 # ADD - Transaction의 mPos, mtree 적용 및 시블링들 검색

---

src/services/signature_requester.cpp
src/services/signature_requester.hpp
src/services/signer_pool.cpp
src/services/signer_pool.hpp
src/services/signer_pool_manager.cpp
src/services/signer_pool_manager.hpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp
tests/services/test.cpp

- 기획서에 따르면 TX 취합 타이머가 시작되면, 서명을 요청할 서명자들을 선출해야한다.
* https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/47022295/GE2.+Protocol+Diagram
* `TransactionCollector#handleMessage` 에서 타이머 시작과 동시에 서명요청하는 함수 호출(`requestSignatures`)
* 서명 요청할 서명자들을 선출하는 로직이 종전의 코드에서는 `SignerPoolManager`에 존재했음. 그래서 `SignerPool`로 이동
* `SignerPool`로 함수 이동하고, `getSelectedSigners` 로 이름 변경.
- 서명자들을 랜덤하게 뽑는 코드에 대한 테스트 추가
https://thevaulters.atlassian.net/secure/RapidBoard.jspa?rapidView=21&projectKey=GEN&modal=detail&selectedIssue=GEN-50

# EDIT - 서명요청할 Signers 뽑는 코드 수정

---

src/application.hpp
src/services/signature_requester.cpp
src/services/transaction_collector.cpp
src/services/transaction_generator.cpp
src/services/transaction_pool.cpp
src/services/transaction_pool.hpp
tests/services/test.cpp

- TransactionPool을 여러곳에서 접근하고 있어서 동시성 제어가 필요하다.
- 따로 클래스로 분리하고, 뮤텍스를 통해서 동시성제어를 하도록 구현

# EDIT - TransactionPool 클래스로 분리

---

include/base64.hpp
src/utils/bytes_builder.hpp
tests/utils/test.cpp

- 다양한 타입의 변수를 byte vector 로 만드는 클래스입니다. static이 아니라 필요할 때마다 선언해서 사용해야 합니다. 타입을 계속 변환하는 것이 힘겨워 보였어요.
- Botan이 secure_vector를 뱉는 터라(도대체 뭐라고?!)  마크롱의 base64.hpp를 include에 넣었습니다.

 #ADD - added ByteBuilder class to make byte vector

---

src/chain/signer.hpp
tests/modules/CMakeLists.txt
tests/services/CMakeLists.txt

- signer.hpp에 storage path 변경
- modules, services에 leveldb 관련 cmake 추가

 # EDIT - signer.hpp에서 leveldb 빌드 오류 수정

---

src/chain/block.hpp
src/services/block_generator.cpp
src/services/block_generator.hpp
src/services/message_factory.hpp
src/services/signature_requester.cpp
tests/services/test.cpp

- 기존에 주석처리되었던 PartialBlock 생성 로직을 주석해제
- BlockGenerator#generatePartialBlock
* 임시블럭 생성에 필요한 데이터를 입력하고, 임시블럭을 리턴한다.
* MessageFactory 관련 코드 때문에 빌드가 안돼서 임시 주석처리, 다음 PR에서 처리할 것.

# EDIT - PartialBlock 생성하는 로직 수정

---

src/services/storage.cpp

- [GE5 Data Structure 7.1 Transaction](https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/51183867/GE7.+Storage+Structure) 적용

 # EDIT - readBlock 함수에서 transaction 규격 재적용

---

src/services/storage.cpp
tests/services/test.cpp

- readBlock에서 DB에 height가 없다면 return tuple(-1,"","")로 해줌

 # EDIT - Height가 없을 때의 처리

---

src/utils/hmac.hpp

- 일반 key를 받아 sha256 후 그 key를 이용하여 검증 및 생성하도록 하였습니다.

 # EDIT - HMAC 검증 및 생성 수정

---

src/services/signer_pool.cpp
src/services/signer_pool.hpp
src/utils/time.hpp

# FIX - Year 2038 problem.

---

src/chain/block.hpp
src/chain/types.hpp
src/services/block_generator.cpp
src/services/block_generator.hpp
src/services/message_factory.hpp

- Block의 구조를 정의함
참조: https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/51707911/GE4.+Block+Structure

# ADD - 블럭 구조 정의

---

src/services/block_generator.cpp
src/services/block_generator.hpp
src/services/signature_pool.cpp
src/services/signature_pool.hpp
src/services/signature_requester.cpp
src/services/signature_requester.hpp
tests/services/test.cpp

- 일정조건에 도달하면 블럭을 생성한다.
* 서명 1개 수집되면 블럭 생성
* 테스트 코드 추가
참조: https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/51707911/GE4.+Block+Structure

# ADD - 블럭 생성

---

src/modules/communication/msg_schema.hpp

- MSG_BLOCK 에 대한 Json schema를 수정하였습니다.

 # EDIT - MSG_BLOCK json schema 수정

---

src/services/transaction_collector.cpp

- 종전의 코드에서는 Transaction 수집 타이머가 시작되자마자 서명을 요청했다.
- Timer가 만료된후에 서명요청하고 블럭을 생성하는게 맞기 때문에 그렇게 수정함.

# EDIT - Transaction Timer가 만료된후 서명요청 및 블럭 생성하도록 수정

---

CMakeLists.txt
src/chain/merkle_tree.hpp
src/config/config.hpp
src/services/block_generator.cpp
src/services/signature_requester.cpp
src/services/signer_pool.cpp
tests/modules/CMakeLists.txt
tests/modules/test.cpp

- 프로그램의 동작을 제어하기 위한 상수들을 한 곳에서 관리하도록 config.hpp에 넣음
- knowledge 관련 상수들은 다른 PR에서 진행할 예정
https://thevaulters.atlassian.net/browse/GEN-134

# ADD - 흩어져있는 상수들 한곳으로 정리

---

src/modules/communication/msg_schema.hpp

- MSG_BLOCK, MSG_TX Json-schema 수정

 # EDIT - Json Schema 수정

---

src/chain/types.hpp
src/services/block_generator.cpp
src/services/signature_pool.cpp

- 8bytes 정수형 숫자가 아니라 string 타입이라서 수정함

# EDIT - Block height type 변경

---

.travis.yml

- 현재 빌드하는데 소요 시간 30분
- 빌드에 필요한 packages를 설치해둔 docker 환경 구성하고, 이를 빌드에 사용
- docker pull doscode/merger-build-env:1.1
- docker run -d --name `build-env` --rm -i -t doscode/merger-build-env:1.1 bash
- 이후 docker exec build-env sh -c ""로 도커안에서 수행될 커맨드 전달
- python3.6 python3-pip python3-setuptools clang git libboost-all-dev autoconf clang-tidy curl
- cmake wheel pyyaml
- git clone https://github.com/lz4/lz4.git
- git clone https://github.com/randombit/botan.git
- git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
- ~/clang-tidy-checker.sh
- sh -c 커맨드로 if 구문 처리하는게 까다로워서 .sh 파일 제작
- clang-tidy 검사 포함 : 12분
- clang-tidy 검사 제외 : 6분

 # EDIT - travis ci (using docker to build)+

---

main.cpp
src/application.cpp
src/application.hpp
src/services/block_generator.cpp
src/services/setting.hpp
src/services/signer_pool_manager.cpp
src/services/transaction_generator.cpp

- setting 을 singletone으로 바꾸었습니다.
- Application의 transactionpool에서 Application을 다시 참조하여 make_shared 과정에서 무한 루프에 빠집니다.

 # HOTFIX - made setting singleton to avoid infinite making object

---

CMakeLists.txt
docker-compose.yml

# ADD - docker compose 추가

---

docker-compose.yml

- 배포완료되면 백그라운드모드로 어플리케이션 동작하도록 수정
- --build . 이후에 " 따옴표가 빠져서 추가

# FIX - docker-compose 오류 수정

---

.travis.yml

- lib/leveldb 빌드 커맨드 제거
- CMakeLists.txt에 `add_subdirectory(lib/leveldb)`가 있음

 # EDIT - travis 설정

---

src/chain/types.hpp
src/config/config.hpp
src/modules/bootstraper/block_synchronizer.hpp
src/modules/bootstraper/boot_straper.hpp
src/services/block_processor.cpp
src/services/block_validator.hpp

- bootstraper : blockSynchronizer구동, MSG_UP 날림
- blockSynchronizer : services/blockValidator로 block 검증, MSG_BLOCK, MSG_REQ_BLOCK 처리
- bootstraper : BPscheduler, MessageFetcher 구동

# ADD - bootstraper & blocksynchronizer 

---

.gitignore

- production에서 사용되는 환경변수들이 저장된 env파일을 VCS에 저장할 필요가 없음

# EDIT - .env 파일 git ignore

---

docker-compose.yml
main.cpp
src/config/config.hpp
src/modules/communication/communication.cpp

- 여러 개의 Merger를 하나의 aws instance에서 동작시키기 위해서는 서로 다른 port을 open할 수 있어야 한다.
- port도 입력을 받을 수 있도록 수정

# EDIT - port number 입력으로 받을 수 있도록 수정

---

include/json-validator.cpp
src/application.cpp
src/chain/types.hpp
src/modules/bp_scheduler/bp_scheduler.cpp
src/modules/bp_scheduler/bp_scheduler.hpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp

- sstream이 없어서 생긴 문제.
- json-schme-validator repo에 이슈로 리포팅함
* https://github.com/pboettch/json-schema-validator/issues/41
- 임시로 sstream 포함시켜서 해결함
- **다른 개발자들이 clang-format 안돌려서 이상한 것도 수정됨**

# FIX - json-validator.cpp 에러

---

.travis.yml
docker-compose.yml

- docker-compose의 pull 하는 버전을 latest으로 수정
- travis도 latest로 수정

# EDIT - docker image 최신버전으로 pull 받도록 수정

---

src/modules/communication/merger_client.cpp
src/modules/communication/merger_client.hpp

- Setting 객체의  MergerInfo를 이용하여 다른 Merger에게 Message를 보낼
수 있도록 함.

 # EDIT - 다른 Merger에게 message를 보낼 수 있게 설정

---

src/modules/communication/merger_client.cpp
src/services/setting.hpp

# EDIT - address 버그 수정

---

main.cpp
src/application.cpp
src/application.hpp
src/config/config.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/bootstraper/block_synchronizer.hpp
src/modules/bootstraper/boot_straper.hpp
src/modules/bp_scheduler/bp_scheduler.cpp
src/modules/bp_scheduler/bp_scheduler.hpp
src/modules/communication/grpc_util.cpp
src/services/block_processor.cpp
src/services/block_processor.hpp
src/services/message_proxy.cpp
src/services/output_queue.hpp
src/services/setting.hpp
src/services/signer_pool.cpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp
src/utils/random_number_generator.hpp

- BP Scheduler가 Application에 통합되었습니다.
- BP Scheduler의 연속 locking 오류를 수정했습니다.
- BlockProcessor가 MessageProxy에 연결되었습니다.
- TX Collector 코드를 조금 바꾸었습니다.
- BlockProcessor에서 더 다양한 메시지를 처리할 수 있어야 합니다.
- 중복 TX 삭제 기능

# ADD - integrated BP Scheduler into App and etc.

---

src/chain/types.hpp
src/services/block_processor.cpp
src/services/block_processor.hpp
src/services/message_proxy.cpp

- Block Processor에 MSG_REQ_CHECK, MSG_RES_CHECK 처리하는 부분 추가
###변경
- Block Processor 함수 분리

# ADD - added handling MSG_REQ_CHECK to BlockProcessor

---

src/services/input_queue.hpp

- InputQueueAlt에 중복함수가 있어 빌드가 깨지던 문제

 # REMOVE - InputQueueAlt에 중복 함수 제거

---

src/chain/types.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/bootstraper/block_synchronizer.hpp

- 부트스트래핑 중 signer가 메시지를 보낼 때, 혼자 있음에도 부트스트래핑 과정이 길어지는 문제 해결
- signer에게는 관련 에러 메시지 전송

# EDIT - handling MSG from signer in bootstrapping

---

main.cpp
src/chain/types.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/services/argv_parser.hpp
src/services/setting.hpp
src/services/storage.cpp

- main.cpp에 있던 인자 파싱을 ArgvParser 클래스로 이동, 정리
- db 패스 생성은 Storage 클래스에서 하도록 이동
- 한다고 했는데, 적용되지 않았던 clang-format이 적용된 파일들

# EDIT - moved parsing arguments to ArgvParser and so on.

---

src/chain/types.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/bp_scheduler/bp_scheduler.cpp
src/modules/bp_scheduler/bp_scheduler.hpp
src/services/argv_parser.hpp
src/services/block_processor.cpp
src/services/block_processor.hpp
src/services/block_validator.hpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp
src/services/transaction_pool.cpp
src/services/transaction_pool.hpp
src/utils/bytes_builder.hpp
src/utils/type_converter.hpp

- BP 스케쥴러 리팩트
- MSG_BLOCK 수신시 TX풀에서 중복 TX 제거
- TX가 TX 풀에 넣어지기 전 중복 체크

# ADD - Refactoring BP scheulder and Handling of duplicated TXs

---

src/services/storage.cpp
src/services/storage.hpp

- 블록 저장할 때 disk I/O 대량 발생
- batch모드로 저장하여 속도향상
참고 [WriteBatch isn’t what you think it is](https://ayende.com/blog/161412/reviewing-leveldb-part-iii-writebatch-isnt-what-you-think-it-is)

 EDIT - saveBlock in batch*

---

.gitignore
src/chain/types.hpp

- 에러 메시지 타입의 번호를 고정 (컨플루언스에 반영)
- gitignore에 setting.json 추가

# EDIT - edited error message type to fixed numbers

---

src/modules/communication/merger_server.cpp
src/modules/communication/merger_server.hpp
src/modules/communication/protos/protobuf_se.grpc.pb.cc
src/modules/communication/protos/protobuf_se.grpc.pb.h
src/modules/communication/protos/protobuf_se.pb.cc
src/modules/communication/protos/protobuf_se.pb.h
src/modules/communication/protos/protobuf_se.proto

- Protobuf 수정
- SE에게 TX를 받았을 때, MessagHandler에서 처리한 결과에 대한 답을 boolean으로 하도록 함.
- 정상적으로 Input Queue에 도달시 True 아닐시 False를 보내도록함

# EDIT - SE에게 TX 에 대한 msg 상태를 reply하는 부분 수정

---

src/modules/bp_scheduler/bp_scheduler.cpp

- 모든 머저가 IDLE  상태일 때 IDLE 상태가 유지되는 문제를 발견
- 해결해보려고 했는데, 코드가 너무 복잡해서, BP Scheduler 의 메인 알고리즘 부분을 조금 더 단순한 룰로 재작성 (알고리즘은 그대로! 더 나은 코드! 더 명확한 코드!)

# EDIT - re-wrote rescheduling algorithm in BP scheduler

---

include/easy_logging.cpp
include/easy_logging.hpp
src/services/block_processor.cpp
src/services/block_processor.hpp

- logging library ( https://github.com/zuhd-org/easyloggingpp )
- macro를 이용하여 logging option 설정 가능 ( 전체 로그 해제, 특정 레벨 로그 출력 등 )
-

 # ADD - logging library

---

src/application.cpp
src/chain/types.hpp
src/config/config.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/bootstraper/block_synchronizer.hpp
src/modules/bootstraper/boot_straper.cpp
src/modules/bootstraper/boot_straper.hpp
src/modules/bp_scheduler/bp_scheduler.cpp
src/modules/communication/communication.hpp
src/modules/communication/merger_client.cpp
src/modules/communication/merger_server.cpp
src/modules/communication/merger_server.hpp
src/services/block_processor.cpp
src/services/block_validator.hpp
src/services/transaction_collector.cpp
src/utils/safe.hpp

- BlockSynchronizer가 다른 merge와 통신하지 못하는 버그 
-- 원인-1: connection 상태를 확인하는 타이밍이 느려 MergerClient에서 자동 드롭, 
-- 원인-2: MSG_REQ_BLOCK이 MergerServer가 시작하기 전에 보내짐
-- 해결: Bootstraper가 MergerServer가 시작하길 기다림, MergerServer가 메시지를 수신하면 연결 상태 업데이트
- blockraw에서 데이터 길이를 잘못 계산하던 버그
- blockjson에서 tx를 string으로 넘기는 버그
- blockjson에서 hash에 binary 값이 할당 되던 버그
- BlockSynchronizer가 순서대로 MSG_REQ_BLOCK을 보내는 부분이 없음

# EDIT - fixed bugs bewteen communication BProc and BSync

---

src/services/block_processor.cpp

- BytesBuilder#append 에서 size_t를 처리할 수 있는 함수가 없음
- 컴파일할때 모호하다는 에러가 출력돼서 수정함

# FIX - build할때 ambiguous 하다는 에러 수정

---

src/modules/communication/merger_server.cpp
src/modules/communication/merger_server.hpp
src/modules/communication/protos/protobuf_se.grpc.pb.cc
src/modules/communication/protos/protobuf_se.grpc.pb.h
src/modules/communication/protos/protobuf_se.pb.cc
src/modules/communication/protos/protobuf_se.pb.h
src/modules/communication/protos/protobuf_se.proto

- SE로 부터 받은 MSG_TX에 대해 MessageHandler에서 처리한 부분에대한 상태를
SE에 답하도록 함.
- InputQueue에 정상적으로 도달시 SUCCESS
- MessageHandler에서의 unpack 과정에서 validation 실패시 INVALID
- Merger 내부 문제 발생 시 INTERNAL

# EDIT - Merger Server에서 MSG_TX에 대해 답하는 부분수정

---

main.cpp
src/chain/block.hpp
src/chain/transaction.hpp
src/config/config.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/bootstraper/block_synchronizer.hpp
src/modules/communication/merger_client.cpp
src/modules/communication/rpc_receiver_list.hpp
src/services/argv_parser.hpp
src/services/block_processor.cpp
src/services/certificate_pool.hpp
src/services/message_proxy.cpp
src/services/setting.hpp
src/services/signature_requester.cpp
src/services/signature_requester.hpp
src/services/signer_pool_manager.cpp
src/services/storage.cpp
src/services/storage.hpp
src/services/transaction_collector.cpp
src/services/transaction_collector.hpp

- txid의 구조를 변경 및 그에 따른 tx collector의 구조 변경
- transaction 클래스에서 storage 의존성 제거 및 그에 따른 tx collector의 구조 변경
- main.cpp 단순화 (일부 역할을 argv parser로 이동)
- certificate pool 클래스 추가
- block sync에서 2초 이내 재전송 요청 막음
- 블록 생성, 싱크

# EDIT - new TXID

---

include/blockconcurrentqueue.hpp
src/chain/block.hpp
src/chain/signature.hpp
src/config/config.hpp
src/modules/bootstraper/block_synchronizer.cpp
src/modules/communication/http_client.cpp
src/modules/communication/merger_server.cpp
src/modules/message_fetcher/message_fetcher.cpp
src/services/input_queue.hpp
src/services/message_proxy.cpp
src/services/signature_pool.cpp
src/services/signature_pool.hpp
src/services/signature_requester.cpp
src/services/signature_requester.hpp
src/services/storage.cpp
src/services/storage.hpp
src/services/transaction_pool.cpp
src/services/transaction_pool.hpp

- block 객체의 setSupportSignatures 함수의 ambiguity 문제
- 지지 서명의 유효한 블록 높이 문제
- input queue의 blocking queue 및 bulk fetch로 수정
- signature requester의 구조 단순화
- storage 객체의 safe 강화
- leveldb LRU 캐시 사용
- TX pool 에서 삭제된 tx에 접근하는 문제
- 동일 txid 문제는 지난 PR에서 이미 해결되었습니다.

# EDIT - fixed bugs found in release/super-koopa

---

CMakeLists.txt
include/omp_hash_map.h
include/omp_hash_set.h
include/reducer.h
src/services/transaction_pool.cpp
src/services/transaction_pool.hpp
src/utils/type_converter.hpp

- TX Pool을 concurrent-hash-map과 vector 기반으로 수정
- cmake에 OpenMP 추가

# EDIT - fixed bugs found in release/super-koopa (2nd)

---

src/services/transaction_pool.cpp

- for loop에서 size_t를 쓸 경우 transaction_pool의 size가 0 일 때 -1을
하면 문제가 생긴다. 따라서 int로 수정

 # FIX - Inverse - sizet 수정
