gruut/enterprise-merger

- CMakeLists.txt
- src/chain/message.hpp
- src/services/block_generator.cpp
- src/services/message_factory.hpp
- src/services/signature_requester.cpp
- src/services/transaction_fetcher.cpp
- src/services/transaction_fetcher.hpp
- tests/modules/CMakeLists.txt
- tests/services/CMakeLists.txt
- tests/services/test.cpp
- BlockGenerator에서 머클트리를 생성하고 임시블럭의 transaction_root 필드에 데이터를 쓰도록 함
- MessageFactory에서는 임시블럭으로 서명요청 메시지를 생성한다.
- Transaction id가 256바이트형식의 랜덤값을 갖도록 수정함
> # ADD - 임시 블록 생성 및 MSG_REQ_SSIG 메시지 생성

- src/services/signature_requester.cpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- tests/services/test.cpp
- 종전의 코드에서는 서명 요청할 Signers 들의 정보를 따로 저장하고 있지 않아서, 통신 모듈에서 누구에게 서명 요청할지 알수가 없었다.
- `SignerPoolManager` 에서 랜덤하게 Signers들을 뽑아올때 그것들을 따로 저장해서 나중에 통신 모듈에서 랜덤하게 뽑은 Signers들을 가져갈 수 있도록 구현
- 테스트 케이스 추가
* `getSigners -> getSelectedSigners` 순서 종속성이 있어서 테스트 코드에 추가
* `SignatureRequester` 가 request를 보내면 OutputQueue에 사이즈가 0 초과임을 테스트코드에 남김.
> # ADD - 서명 요청할 Signers의 리스트를 저장하도록 함

- .travis.yml
- src/chain/merkle_tree.cpp
- src/chain/merkle_tree.hpp
- src/services/block_generator.cpp
- src/services/block_generator.hpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- tests/chain/test.cpp
- tests/services/test.cpp
- 종전의 코드에서는 머클트리의 루트만 계산하고, 트리는 저장하지 않았다.
- 블럭에 들어갈 머클트리를 저장하기 위해 머클트리 전체를 unordered_map에 저장함
> # EDIT - PartialBlock 생성시 머클트리 저장하도록 수정

- .gitignore
- src/modules/storage/storage.cpp
- src/modules/storage/storage.hpp
- tests/modules/test.cpp
- 먼저 블록헤더에 Transaction List를 저장
- Block ID와 Transaction ID가 주어지면 해당
Transaction ID가 몇번째로 위치하는지 검색한다.
- Test가 끝난 후 소멸자에서 DB 디렉토리를 삭제시켜준다.
> # ADD - Transaction ID 위치 검색, DB 디렉토리 삭제

- src/utils/hmac_key_maker.hpp
- `m_group_domain.get_curve()` 에서 deprecated 되었다고 오류 발생함
- `get_curve`를 제거하고 m_curve를 다른 생성자로 호출해서 초기화함
- `botan_all` 제거
- 다음 버전에서 `get_curve`가 제거될 예정이라고 함
> # FIX - hmac_key_maker 에서 deprecated 오류

- src/modules/communication/grpc_merger.cpp
- src/modules/communication/grpc_merger.hpp
- src/modules/communication/grpc_util.cpp
- src/modules/communication/grpc_util.hpp
- tests/modules/test.cpp
- message type에 따라 hmac을 붙히거나 검증하는 부분 추가.
- hmac이 뒤에 붙으므로 body 사이즈가 필요하다고 생각하여 grpc_util의 detachHeader함수 수정
* detachHeader -> getMsgBody 로 이름 수정
>  # ADD - hmac 검증 및 추가 사용

- src/application.cpp
- src/application.hpp
- src/chain/signer.hpp
- src/services/message_proxy.cpp
- src/services/signer_pool.cpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- src/utils/type_converter.hpp
- tests/services/test.cpp
- MSG_SUCCESS 처리
* `signer_pool_manager` 에서 SignerPool 에 signer 정보를 넣고, MSG_ACCEPT 에 대한 응답을 보냄
- 전역으로 관리하는 SignerPool 를 Application 클래스에 멤버변수로 추가
- SignerPool#pushSigner 테스트 코드 추가
- 현재 SignerPoolManager는 Application 클래스의 멤버변수로 관리되고 있다. SignerPoolManager는 join하려고 하는 signer 와 통신하면서 merger_nonce, shared_secret_key 등을 저장하고 있기 때문에 다수의 Signer가 SignerPoolManager를 접근하면 의도하지 않은 값으로 상태 변수들이 overwrite 될 수 있다. MSG_JOIN 부터 MSG_ACCEPT 까지 통신에 필요한 값들을 적절하게 관리할 수 있어야 한다.
- connection table를 생성해서 signer 당 하나의 entry로 관리해서 MSG_ERROR 또는 MSG_ACCEPT 단계에서 그 entry를 제거하도록 구현 예정
> # ADD - SignerPool에 Signer 추가 및 Signer에게 Accept 메시지 송신 구현

- src/chain/join_temporary_data.hpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- 종전의 코드에서는 다수의 Signers가 SignerPoolManager(Single intance)를 접근하면 m_merger_nonce, m_signer_cert 등 Signer가 JOIN에 필요한 정보들이 overwrite 된다.
- 그것을 막기 위해서는 signer_id 마다 따로 데이터를 관리해야 한다.
- JoinTemporaryData 구조체를 생성하고, SignerPoolManager에서 signer_id 별로 따로 관리하도록 구현.(unordered_map)
> # FIX - 다수의 Signers가 동시에 SignerPoolManager를 접근할때 생길 수 있는 문제 해결

- src/services/input_queue.hpp
- src/services/output_queue.hpp
- InputQueue와 OutpuQueue에서 메시지 엔트리를 패치해올 때, pop_front에 mutex 를 걸었습니다.
- 그런데 잘 생각해 보면 read하는 것은 두 쓰레드가 동시에 할 수 있고, 동일한 엔트리를 가져왔는데, 그 사이에 한 쓰레드가 pop_front 해버리고, 다른 쓰레드가 pop_front를 연속해서 해버리면 두 쓰레드가 가져간 메시지 엔트리는 같은데, 메시지 엔트리가 2개 사라지는 일이 벌어집니다. 
- 따라서 mutex를 read 액션에도 같이 걸어주어야 합니다.
> #FIXED: bug in fetching entry from InputQueue and OutputQueue

- src/chain/types.hpp
- src/services/input_queue.hpp
- src/services/output_queue.hpp
- tests/services/test.cpp
- 타입에 MSG_NULL 추가
- 큐가 비어 있을 때 fetch하면 MSG_NULL 메시지가 리턴되도록 수정
- empty() 멤버함수 추가 (fetch하기 전에 큐가 비어 있는지 확인하는 걸 권고)
- 약간의 테스트 코드 추가
- 클래스 이름 InputQueueAlt / OutputQueueAlt로 재명명
>  #FIXED - 빈 큐 처리 및 테스트 코드 추가

- src/application.cpp
- src/application.hpp
- src/chain/transaction.hpp
- src/chain/types.hpp
- src/services/block_generator.cpp
- src/services/message_proxy.cpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- src/services/transaction_collector.cpp
- src/services/transaction_collector.hpp
- src/services/transaction_fetcher.cpp
- src/utils/rsa.hpp
- src/utils/type_converter.hpp
- tests/modules/CMakeLists.txt
- tests/services/test.cpp
- MSG_TX을 수신했을때 Transaction을 Pool에 저장할 수 있어야 한다.
- MSG_TX가 들어왔을때 TransactionCollector#handle_message 에서 파싱하고, 서명검증한다. 그리고 서명이 valid하면 TransactionPool에 추가한다.
- TransactionPool을 global하게 접근할 수 있도록 수정(Application 클래스의 멤버변수로 추가 및 관련 getter 함수 추가)
- Timestamp를 uint64_t 형식으로 저장하기 위해서 유틸 함수 추가함(`toTimestampType`)
* 비트 플래그 및 비트 쉬프트 이용해서 구현
* Timestamp 관련 코드 추후 이 함수를 이용해서 변경할 예정
- RSA utils
* `static bool doVerify(Botan::RSA_PublicKey &rsa_pk)` -> `static bool doVerify(Botan::Public_Key &rsa_pk)` 매개변수 타입 변경
*  Botan::Public_Key 가 Botan::RSA_PublicKey 의 base 클래스이므로 범용성에서 Botan::Public_Key 를 받는게 더 적절함
- 관련 없는 코드 일단 주석처리함. 다음 PR에서 주석해제하면서 서명요청 기능 구현할 것
https://thevaulters.atlassian.net/secure/RapidBoard.jspa?rapidView=21&projectKey=GEN&modal=detail&selectedIssue=GEN-45
> # ADD - Transaction을 TransactionPool에 넣는 코드 구현

- CMakeLists.txt
- src/chain/signer.hpp
- src/chain/transaction.hpp
- src/services/signer_pool.cpp
- src/services/signer_pool.hpp
- src/services/transaction_collector.cpp
- src/services/transaction_collector.hpp
- src/services/transaction_fetcher.cpp
- src/services/transaction_fetcher.hpp
- src/services/transaction_generator.cpp
- src/services/transaction_generator.hpp
- src/utils/time.hpp
- tests/services/CMakeLists.txt
- tests/services/test.cpp
- TransactionCollector의 타이머가 trigger 되는 순간, 신규 Signers에 대해서 Transaction을 생성해야 한다.
- SignerPool#create_transactions 구현
* SignerPool은 signers를 parameter로 `TransactionGenerator#generate`를 호출한다.
* `TransactionGenerator#generate`에서는 새로운 Transaction을 생성해서 TransactionPool에 넣는다.
- Signer#isNew
* 새로운 Signer인지 검사하는 로직
- Time Util 생성
* Transaction의 생성시간을 저장해야 한다.
* 다른 곳에서 자주 사용하고 있으므로 유틸 클래스로 생성함. 추후 리팩토링 필요
- storage 를 이용하게 되면서 service 테스트 cmakelist 수정
- 테스트코드 추가
- 빌드 성공을 위해서 TransactionFetcher 관련 코드 수정함
* 이 PR과 관계는 없지만 우선 빌드가 안돼서 필요없는 코드 제거
참조: https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/47022295/GE2.+Protocol+Diagram
>  # ADD - 신규 signer의 cert를 저장하기 위한 Transaction 생성 구현

- src/modules/communication/grpc_merger.cpp
- src/modules/communication/grpc_util.cpp
- signer와 rpc에서 openChannel시 파싱할때 길이를 잘 못 지정하여 더미값이
들어갔었음
- header를 파싱할 때 endian 문제로 수정
>  # FIX - sender-id parsing 문제 해결

- src/utils/bytes_builder.hpp
- BytesBuilder에 있던 버그를 고쳤습니다.
- 직접 출력해서 결과를 확인했으니까 믿고 쓰셔도 됩니다.
- uint64_t를 바꿀때 마스킹처리에서 shift를 한칸 더 했음
- hex 길이랑 바이트 길이랑 헷갈림
- istringstream이 이렇게 쓰는 게 아닌게벼.
>  # FIX - fixed bugs on BytesBuilder

- src/chain/block.hpp
- src/modules/communication/grpc_merger.cpp
- src/modules/communication/grpc_util.cpp
- src/services/block_generator.cpp
- src/services/message_factory.hpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- src/services/signer_pool_manager.cpp
- src/utils/type_converter.hpp
- `BlockGenerator#generatePartialBlock` 에서 임시블럭을 생성
-  MessageFactory에서는 서명요청 메시지를 생성해서 OutputQueue에 넣음
* Base64로 인코딩하는 코드가 중복으로 존재해서 TypeConverter에 `toBase64Str` 추가
- SignerPool 코드 수정
* 이 PR과는 직접적으로는 관계없지만, sender 정보를 가져올 필요없이 `receiver_id` 를 직접 가져올 수 있어서 수정
- PartialBlock의 sent_time 필드 제거
* 메시지 송신할때 필요한 필드이므로, 임시블럭에는 필요없는 데이터
- grpc 관련 통신 버그
* 일관되게 엔디안 처리가 안돼서 receiver_id가 매 요청마다 다르게 들어옴(Join 할때는 id가 3203230이고, openChannel 에서는 52가 들어옴)
* 일단 52로 들어오는게 맞으므로, reverse로 임시처리함.
https://thevaulters.atlassian.net/secure/RapidBoard.jspa?rapidView=21&projectKey=GEN&modal=detail&selectedIssue=GEN-47
> # ADD - MSG_REQ_SSIG 메시지 보내도록 구현

- src/application.hpp
- src/chain/signature.hpp
- src/modules/message_fetcher/message_fetcher.cpp
- src/services/message_proxy.cpp
- src/services/signature_pool.cpp
- src/services/signature_pool.hpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- src/services/signer_pool_manager.cpp
- src/services/transaction_collector.cpp
- src/services/transaction_collector.hpp
- Application 클래스에 SignaturePool가 stl 컨테이너 형태로 선언되어있었음. MSG_SSIG(Signer가 보내주는 서명 메시지)를 처리하고 서명을 저장해야 하므로 signature_pool 클래스를 생성
* 서명을 pool에 넣기 전에 Signer의 서명을 검증하는데, 검증하는 작업은 다음 PR에서 진행
- signature.cpp -> signature.hpp 로 수정
- SignatureRequester
* `startSignatureCollectTimer`를 주석해제. timer는 일정시간 서명을 취합하고 expire되면 블럭을 생성하도록 함(블럭 생성하는 것은 다음 PR에서 진행)
- ETC
* signer_pool_manager
* join 시 signer_cert를 base64 디코딩없이 바로 저장하고 있어서 디코딩 후 저장하도록 수정
* MessageFetcher 가 종전의 코드에서는 input_queue에서 3초마다 하나씩 꺼내왔는데, 1초마다 가져오도록 수정(테스트 용이를 위해서)
* TRANSACTION_COLLECTION_INTERVAL_SEC 를 seconds로 변경
>  # ADD - Signer가 보낸 Signature를 Pool에 넣는 코드 구현

- src/application.cpp
- src/application.hpp
- src/chain/signer.hpp
- src/services/signature_pool.cpp
- src/services/signature_requester.cpp
- src/services/transaction_collector.cpp
- src/services/transaction_generator.cpp
- src/utils/rsa.hpp
- src/utils/type_converter.hpp
- `signature_pool.cpp`
* Signer로부터 온 서명을 검증하는 코드를 구현
* json 형태로 넘어온 `signer_id` 를 파싱하기 위해 기존의 `TypeConverter::toTimeStampType`을 `TypeConverter::to8BytesArray`로 함수명 변경하고 그것을 사용함
- Appliction 클래스에 임시블럭을 블럭 생성 전에 저장하도록 구현
* Signer에게 서명요청하기 위해 임시블럭을 전송하고, Merger는 MSG_SSIG(서명 메세지)를 받게 된다. SignaturePool에서 Signer가 보내온 Signature를 서명 검증하는 과정에서 merger_id 및 height 그리고 tx_root가 필요하기 때문에 임시블럭에 대한 정보가 필요하다.
* SignatureRequester#requestSignatures 에서 임시블럭을 Signer에게 보내기 전에 저장.
- ETC
* 중복되는 함수 템플릿으로 리팩토링함
> # ADD - MSG_SSIG 서명 검증하는 코드 구현

- src/chain/block.hpp
- src/chain/transaction.hpp
- src/chain/types.hpp
- src/services/block_generator.cpp
- src/services/message_factory.hpp
- src/services/signature_pool.cpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- src/services/transaction_collector.cpp
- src/services/transaction_generator.cpp
- src/utils/type_converter.hpp
- sender_id_type -> merger_id_type
* 변수명 변경
* 설계서에 따르면 merger_id_type은 64비트가 되어야 함.
* block.merger_id = 1로 하드코딩, config 관련 파일 생성되면 변경할 것.
- `Transaction`의 sent_time 타입 변경
* 현재 대부분의 비트를 vector 컨테이너로 핸들링하고 있어서, array를 vector로 converting하는게 번거로움.
- stl container::insert -> BytesBuilder
* 바이트 array를 생성하기 위해 종전의 코드에서는 vector를 하나 선언하고, `insert`를 통해 데이터를 붙였다.
* Bytes를 쉽게 생성할 수 있는 유틸 클래스가 생겨서, 그것을 통해 바이트를 쉽게 생성할 수 있도록 리팩토링
- `TypeConverter`
* 함수명이 애매한 것들을 변경함
* 일부 inline 이 가능한 함수들에 inline 키워드 추가
* `decodeBase64` 함수 추가
* 일부 코드에서 Botan::base64_decode 에 대한 의존성을 줄이기 위함
> # REFACTOR - sender_id 변수명 변경 및 타입 관련 리팩토링

- src/modules/communication/communication.cpp
- src/modules/communication/merger_client.cpp
- src/modules/communication/merger_client.hpp
- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- src/modules/communication/message_handler.cpp
- src/modules/communication/message_handler.hpp
- src/modules/communication/rpc_receiver_list.hpp
- src/modules/message_fetcher/out_message_fetcher.cpp
- src/modules/message_fetcher/out_message_fetcher.hpp
- src/utils/compressor.hpp
- 각 역할을 수행하도록 MergerServer, MergerClient, MessageHandler 클래스로 분리
- Signer와 rpc 통신을 비동기 처리로 수정
- Signer의 Rpc 데이터를  보관하기 위해 RpcReceiverList를 singletone으로 구현
- output queue에서 데이터를 가져오기위해 OutMessageFetcher 클래스 작성
* 기존에 작성 해 놓으신 MessageFetcher 클래스의 구조와 동일
- @grpc_util.hpp 
- 현재 기존에 작성해놓았던 Rpc로 테스트 중이기때문에 수정하거나 삭제하지 않습니다.
> # REFACTOR - MergerRpc 수정

- src/chain/block.hpp
- src/services/block_generator.cpp
- src/services/block_generator.hpp
- src/services/signature_pool.cpp
- src/services/signature_requester.cpp
- src/utils/bytes_builder.hpp
- tests/services/test.cpp
- PartialBlock 생성할때 transactions를 저장하도록 수정
* 블럭 생성할때 (signature_requester.cpp:94) transactions 가 빈 vector로 넘어감.
* 그 이유는 async_wait를 boost io_serv job_queue에 등록 시점에는 transactions 가 있지만, timer가 만료되어서 핸들러가 실행되는 시점에는 transactions가 파괴되어 남아있지 않게 된다.
* 그래서 블럭을 생성할때 transactions size가 0이라서 블럭을 생성하지 못하는 버그
- signature_requester.cpp (54)
* max -> min, 논리적 오류
- signature_pool.cpp
* size를 무조건 0으로 리턴하고 있는 버그
- BytesBuilder#append
* uint32_t를 처리할 수 있도록 함수 추가
* 다른 append 함수들을 하나로 합칠 수 있을 것 같지만 일단 추가
참조: https://thevaulters.atlassian.net/wiki/spaces/SGN/pages/51707911/GE4.+Block+Structure
> # EDIT - 블럭 생성 버그 수정 및 블럭 생성시 서명

- src/config/config.hpp
- src/services/signer_pool.cpp
- src/services/signer_pool.hpp
- `SignerPool`
* m_signer_pool의 자료구조를 deque -> list로 변경
* Signer가 추가되거나 삭제되는 일이 빈번하기 때문에 list가 적절하다.
* 다수의 Signer가 SignerPool을 조작하는 연산을 하게 되면 iterator, pointer, reference가 무효화되기 때문이다.
* list의 경우 노드 기반 컨테이너이기 때문에 list::begin() 부터 순차적으로 elememt를 찾아야 하기 때문에 `find` 함수가 iterator를 리턴하도록 수정
* push_mutex, update_mutex 를 잘못 사용하고 있는 함수들 수정
* `find`, `getNumSignerBy` stl 이 제공하는 알고리즘으로 수정
참고자료: https://books.google.co.kr/books?id=RPnWe6QKnCcC&pg=PA11&lpg=PA11&dq=effective+stl+chapter+1&source=bl&ots=ipmCBZihSq&sig=177WGTbzrHwvI1VmVrgFvPDEfGk&hl=ko&sa=X&ved=2ahUKEwiHprGY4ZbfAhXZAYgKHTB2BeoQ6AEwDHoECAoQAQ#v=onepage&q=effective%20stl%20chapter%201&f=false
> # REFACTOR - PR #106 문제를 해결하기 위한 준비

- src/chain/types.hpp
- src/services/signer_pool_manager.cpp
- tests/services/fixture.hpp
- tests/services/test.cpp
- MSG_SUCCESS 메시지 검증을 위해서는 `shared_secret_key`를 접근할 수 있어야 한다.
- 하지만 종전의 코드에서는 `join_temporary_table` 가 private member 였기 때문에 접근할 수 없었다.
- `SingerPool#pushSigner` 이후에나 key를 접근할 수 있었기 때문에 `MSG_SUCCESS`를 받는 통신 모듈 입장에선 아직 shared_key가 signer_pool에 들어가지 않았으므로 접근할 방법이 없었다.
- `MSG_RESPONSE_1` 단계에서 SignerPool에 Signer를 넣는다. (SignerStatus::TEMPORARY 상태의 Signer)
- `MSG_SUCCESS` 단계에서 `updateStatus`를 통해 Signer의 상태를 업데이트한다.
- SignerPool#updateStatus test 케이스 추가
> # ADD - HMAC 검증을 위해 통신모듈에서 shared_secret_key를 접근할 수 있도록 지원

- src/chain/join_temporary_data.hpp
- src/config/config.hpp
- src/modules/communication/message_handler.cpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- src/utils/time.hpp
- tests/utils/test.cpp
- 종전의 코드에서는 Signer가 네트워크에 Join할때 deadline 을 두지 않고, 키교환을 수행한다. 일반적으로 수초 내에 키교환이 완료되어야 정상이다.
- `Time::from_now` 구현
* argument 값에 따라 현재 시간으로부터 몇초 후의 값을 리턴한다
- SignerPoolManager
* `m_join_temporary_table[receiver_id]->expires_at = Time::from_now(10);` 10초 뒤에 끝나지 않으면 expire 하도록 함
* 만료되면 MSG_ERROR 메시지 송신 및 temporary table entry, SignerPool의 receiver_id에 해당하는 entry를 flush 시킴.
> # EDIT - MSG_JOIN 수신이후 10초 이내 키교환 완료하지 못하면 중단하도록 구현

- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- src/utils/rsa.hpp
- 종전의 코드에서는 서명 검증하는 로직이 string concatenate 후에 검증했다. Signer 쪽에서도 그렇게 구현이 되어있었음.
- Bytes 형식으로 처리가 되어야 하므로, Bytes 형식으로 처리하도록 수정
- 서명하는 로직도 마찬가지
> # EDIT - Signature 검증 및 sign 로직 변경

- src/chain/merkle_tree.hpp
- src/chain/types.hpp
- src/services/signature_requester.cpp
- src/services/transaction_collector.cpp
- src/services/transaction_generator.cpp
- src/utils/bytes_builder.hpp
- src/utils/sha256.hpp
- src/utils/type_converter.hpp
- tests/chain/test.cpp
- transaction_id_type의 타입을 vector -> array로 변경함
- `signature_requester.cpp`
* `makePartialBlock` 에서 transaction_id가 설계서와 다르게 sha256으로 되어있었음, 설계서에 따르면 Tx id는 256bit이고, tx-digest가 sha256 타입이다.
* 현재 Merkle tree를 생성할때 tx_digests로 생성해야 하는데 종전의 코드에서는 단순히 transaction_id를 sha256해서 넘겨주었다.
- `transaction_collector.cpp`
* 타입에 맞게 코드 수정
- `transaction_generator.cpp`
* `generateTransactionId` 타입에 맞게 코드 수정
- `sha256.hpp`
* `hash(array)` 추가
* 앞으로 array를 처리할 곳이 많아서 함수 추가함
- `type_converter.hpp`
* `bytesToArray` 추가
- `merkle_tree.hpp`
* tx_digests를 생성해서 MerkleTree#generate 에 넘겨주는 것보다 generate에서 직접 생성하는게 맞다고 판단해서 수정함
> # EDIT - Transaction id type 변경

- src/chain/types.hpp
- src/services/block_generator.cpp
- src/services/message_factory.hpp
- src/services/signature_pool.cpp
- src/services/signer_pool_manager.cpp
- src/utils/type_converter.hpp
- tests/utils/test.cpp
- Merger id type을 uint64_t 에서 vector<uint8_t>으로 변경함
* 이전에는 고정 64bit였는데, Merger id가 64bit로 표현가능한 숫자 범위를 넘어갈때를 대비해서 vector로 변경
* Merger id를 bytes로 변환할때 `TypeConverter::toBytes`를 통해 little endian 형식의 bytes vector를 생성했다. BytesBuilder에서는 Big endian 형식으로 바이트 vector를 만들기 때문에 통일성을 위해 big endian 형식으로 변경함
* `TypeConverter::toBytes`로 변환된 바이트를 정수값으로 변환시키기 위해서 `digitBytesToIntegerStr`를 추가
> # EDIT - Merger id type 변경

- src/services/block_generator.cpp
- src/services/signer_pool_manager.cpp
- src/services/transaction_generator.cpp
- src/utils/type_converter.hpp
- tests/utils/test.cpp
- toBytes는 어떤 타입과 관계없이 바이트로 만들 것 같은 오해가 생긴다.
- integer -> bytes로 변경할때 사용되고 있으므로, integerToBytes로 함수명 변경함
> # EDIT - toBytes -> integerToBytes 로 함수명 변경

- src/chain/block.hpp
- src/chain/message.hpp
- src/chain/types.hpp
- src/services/block_generator.cpp
- src/services/message_factory.hpp
- src/utils/type_converter.hpp
- tests/modules/test.cpp
- 설계서에서 8바이트이므로 `using local_chain_id_type = std::array<uint8_t, S>` 로 변경
- integer -> array로 변환하는 유틸 함수 추가(`integerToArray`)
- array로 변경됨에 따라 관련 코드 수정
> # EDIT - local_chain_id_type 1바이트를 8바이트로 수정

- main.cpp
- src/application.cpp
- src/chain/signer.hpp
- src/config/config.hpp
- src/modules/message_fetcher/message_fetcher.cpp
- src/modules/message_fetcher/out_message_fetcher.cpp
- src/services/output_queue.hpp
- src/services/signature_pool.cpp
- src/services/signature_pool.hpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- src/services/signer_pool.cpp
- src/services/signer_pool_manager.cpp
- src/services/transaction_collector.cpp
- src/services/transaction_generator.cpp
- src/services/transaction_generator.hpp
- tests/services/test.cpp
- 현재는 지지 서명이 모두 모이더라도 timer가 만료되어야 블록을 생성하도록 되어 있음. 만료되기 전에라도 블록을 생성하도록 수정.
- 서명자의 인증서가 새로운 것인지 아닌지 검사하는 부분 수정 (설령 DB에 있어도 인증서가 새로운 것이면 TX을 생성해야함)
- 새로운 인증서에 대한 TX를 1개만 만들도록 수정
- config에 상수 추가 및 적용
- OutputQueueAlt의 id_type 적용
- 그외 사소한 내용
>  # ADD - faster block generation when gathering max ssigs

- src/modules/communication/message_handler.cpp
- src/services/block_validator.hpp
- src/utils/compressor.hpp
- tests/utils/test.cpp
- 원인 : LZ4 압축 함수 문제
* LZ4 압축을 할때 destination의 capacity를 지정한다. 수정 전에는
capacity 사이즈 그대로 데이터를 리턴하여 압축되고 남은 사이즈만큼
더미값이 들어가 있었다.
- 해결 : 압축된 사이즈로 반환하도록 함수 수정
- compress/decompress 함수를 사용하는 부분 수정
>  # FIX - Compressed msg를 전송할 수 없던 문제 해결

- .travis.yml
- CMakeLists.txt
- include/curlpp.hpp
- my_setting.json
- src/modules/communication/http_client.cpp
- src/modules/communication/http_client.hpp
- src/modules/communication/merger_client.cpp
- src/modules/communication/merger_client.hpp
- src/services/setting.hpp
- tests/modules/CMakeLists.txt
- tests/modules/test.cpp
- HttpClient 추가
* 주소(address + port)를 입력받아 새로운 객체를 생성하고, post하면 해당 주소로 request가 가도록 수정
* 테스트 코드로 SE에 request가 가는 것을 확인했지만, 실제 블럭이 생성된 이후에 요청이 제대로 가는지 테스트는 못함(**현재 Signer쪽 버그때문에 테스트 못함**)
- 실제 SE로 요청보내는 곳 수정(merger_client)
- my_setting.json address, port를 추가 및 수정, ServiceEndpointInfo에 port 필드 추가
> # ADD - Merger가 SE로 MSG_HEADER를 보낼 수 있도록 구현

- src/services/signature_pool.cpp
- src/services/signature_requester.cpp
- 루이지 테스트에서 발견된 MSG_SSIG를 검증하는 루틴에서 chain_id를 빠뜨린 버그를 수정했습니다.
- 디버그용 메시지 출력을 삭제한 건 덤. (루이지에서 잘 되는 거 확인 됨)
>  # FIX - fixed a bug of missing chain_id on louise run

- main.cpp
- src/application.cpp
- src/application.hpp
- Application에서 사용하는 모듈/서비스가 다시 Application을 참조할 경우 hpp/cpp 나눔이 필수
- 컴파일은 되나 Application이 생성이 안되어 멈추어 있는 경우를 몇 차례 확인. 클래스가 서로 참조하므로 순환 참조가 어떻게 이루어지는지 파악하기가 어려워짐
- 스테이지 개념을 도입한 Application에서는 외부에 모듈을 생성하고 이를 등록하도록 하였으나 Application 객체의 역할이 main.cpp로 옮겨지는 것
- 상기와 같은 사항들을 정리하도록 하기 위해서 Application 객체가 생성시간에 생성해야하는 클래스를 제한하여 순환참조에 따른 문제를 완화하도록 setup에서 클래스를 생성하고 모듈을 등록하도록 함.
> # REFACTER - improved application structure

- src/services/signer_pool_manager.cpp
- src/utils/random_number_generator.hpp
- src/utils/type_converter.hpp
- 우연이지만, 루이지 테스트 도중에 dos가 ID를 문자열로 그냥 보냈음.
- 규칙대로 머저가 base64 디코딩을 하였더니, merger가 바로 종료
- 이에 대한 try/catch 삽입
- botan base64 관련 코드가  type_converter에만 있도록 수정 (중앙 관리?)
> # FIX - handling Botan::Base64_decode exception

- src/config/config.hpp
- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- src/services/input_queue.hpp
- src/services/output_queue.hpp
#문제
- rpc server에서 받은 메시지를 MessageHandler에게 넘겨 unpack하는 과정이
순차 처리였음.
#해결
- 메시지를 받아 unpack하는 과정을 io_service에 post 하는 형태로 바꿈
#기타
- InputQueueAlt / OutputQueueAlt 클래스에 size() 함수 추가
- MergerSrever의 recvMessage() 에서 InputQueue의 size가 특정 값보다
커지면 completion_queue(rpc_queue)에서 InputQueue로 보내지 않게 함
- MergerServer의 recvMessage() 에서 Sleep 이 더이상 필요없다고 생각하여
삭제. 메시지가 없을 때는 Next() 부분에서 더이상 진행이 안되는 것을
확인하였음.
* 현재 컴퓨터의 문제로 테스트는 해보지 못한 상태입니다.
>  # REFACTOR - rpc server에서 다수 메시지 발생 시 처리속도 문제 해결

- .gitignore
- main.cpp
- src/services/setting.hpp
- src/services/storage.cpp
- src/services/storage.hpp
- 프로그램 실행 시 --dbpath로 DB 디렉토리 경로를 입력받을 수 있게 설정
- 기본(입력 하지 않았을때) DB 디렉토리 경로 : --dbpath=./db
- setting_json에 이 정보를 담아서(["dbpath"]) Setting 객체의 m_db_path
멤버 변수에 저장
- 여기서 setting_json의 스키마 검사는 피하도록 ["dbpath"]는 erase
- Storage 클래스에서는 Setting 객체의 함수인 getMyDbPath()를 호출하여
해당 경로를 적용
>  # ADD - DB 디렉토리의 경로를 설정 및 적용

- src/chain/join_temporary_data.hpp
- src/chain/types.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/services/argv_parser.hpp
- src/services/signer_pool_manager.cpp
- src/services/signer_pool_manager.hpp
- src/utils/hmac_key_maker.hpp
- src/utils/type_converter.hpp
- 잘못된 값이 넣어져 GFp 클래스에서 Exception이 발생하는 경우 signer에게 오류 메시지 전송
- 서명자 조인 중 잘못된 접근을 차단하고 오류 메시지 전송
- 관련 코드의 가독성 향상을 위해 코드 정리 (디버깅용 오류 메시지 삽입)
- boostraping 중 join 메시지를 보냈을 때, boostraping 시간이 늘지 않음 (현재 signer는 관련 오류 메시지에 대한 처리를 하지 않음)
- boostraping이 끝나고 잘 조인됨
- Intel Xeon E3-1230v3에서 1시간 30분 이상 문제없이 동작
- BP 스케쥴러 초기 비정상 동작 확인 (signer가 1기 이상 연결되어 있어야 함) - 치명적이지 않지만 수정요망
- 정상인 경우 (예상)
```
BPS: sendPing(TUVSR0VSLTE=,1,IDLE)
BPS: sendPing(TUVSR0VSLTE=,1,PRIMARY)
BPS: sendPing(TUVSR0VSLTE=,1,PRIMARY)
....
```
- 현재
```
BPS: sendPing(TUVSR0VSLTE=,1,IN_BOOT_WAIT)
BPS: sendPing(TUVSR0VSLTE=,1,IDLE)
BPS: sendPing(TUVSR0VSLTE=,1,PRIMARY)
BPS: sendPing(TUVSR0VSLTE=,1,PRIMARY)
...
```
- 시작은 GFp에 관련된 Botan::Exception 처리 (완료)
- 관련된 코드 부분은 서명자 조인 부분 코드 분석
- DH키 교환 코드가 매뉴얼과 다르게 작성된 것 발견
- 안드로이드 서명자 코드 분석, 여기도 …
> #EDIT - handling of GFp exception and its related issues

- src/config/config.hpp
- src/modules/message_fetcher/message_fetcher.cpp
- 5ms당 하나의 메시지만 fetch함
- 200 tps가 최대 속도가 됨
- 1ms마다 스레드를 재우면 오버헤드가 더욱 커짐
- 최소 권장 수면 시간: 5ms
- fetch시 최대 5개씩 처리
- 5ms마다 수행
- 이론적으로 최대 1000tps (블록당 1만 개)
- 얼마나 많은 tps를 지향할지 아직 미정
- (교수님은 400개면 충분하다고)
- 지금같은 방식으로 선형 수행 개수를 5에서 10으로 변경하는 방법
- 또는, io_service로 새로운 스레드를 만들어 병렬처리하는 방법이 있음
- 새로운 스레드로 병렬처리한다면, 레이스 컨디션 문제해결 필요 (MSG 0 err)
>  EDIT - fetch 최대 5개씩 처리

- src/services/block_generator.cpp
- src/services/block_generator.hpp
- src/services/signature_requester.cpp
- src/services/signature_requester.hpp
- 블록 생성 요청이 Asio의 큐에 쌓이다 보니 블록 생성 완료 순서를 보장해주지 않음. 순서가 뒤바뀌었을 때 최신 height 등에 대하여 잘못된 정보를 출력할 수 있음.
- strand을 이용하여 순차적으로 블록을 생성하도록 강제 하였음.
- 블록 생성이 기존 데이터에 영향을 받지 않도록 call-by-value를 이용하여 데이터를 넘겨줌
- 사실 이러한 내용은 블록 저장 속도가 향상 되면, 고민하지 않아도 될 문제이지만 예외를 최대한 배제하는 측면에서 작업
> # FIX - added strand for block genrating one-by-one

- src/chain/merkle_tree.hpp
- src/chain/types.hpp
- src/services/block_processor.cpp
- src/services/storage.cpp
- src/services/storage.hpp
- tests/services/test.cpp
- MSG_RES_CHECK에 block_id를 포함하도록 했음 (이게 없으면 merkle root를 알 수가 없음)
- 관련해서 storage 의 findSiblings의 리턴 타입이 복잡해서 proof_type을 정의했음
- 또 이와 관련해서 MerkleTree의 isValidSiblings의 인자를 proof_type을 받을 수 있도록 했음
- 테스트 코드도 같이 고침
- 컨플루언스에는 이미 반영
> # EDIT - added block_id for MSG_RES_CHECK and edited its related codes

- src/chain/reverse_type.hpp
- src/chain/types.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/bootstraper/block_synchronizer.hpp
- src/modules/bootstraper/boot_straper.hpp
- src/modules/communication/merger_client.cpp
- src/modules/communication/merger_client.hpp
- src/modules/communication/message_handler.cpp
- src/modules/communication/msg_schema.hpp
- src/modules/message_fetcher/message_fetcher.cpp
- src/modules/message_fetcher/out_message_fetcher.cpp
- src/services/block_generator.cpp
- src/services/block_processor.cpp
- src/services/block_processor.hpp
- MSG_REQ_BLOCK(-1)이 왔을 때, 지금까지 생성된 블록이 없다면 MSG_ERROR(88)를 보내 부트스트래핑을 바로 끝내게 함. (만약  BLOCK을 보내는 머저가 있다면, 이는 Queue에 쌓여 block processor가 처리할 것)
- MSG_ERROR가 모든 참여자에게 전송받을 수 있게 수정
- MSG_BLOCK에 mID를 추가하여 보낸 merger를 특정할 수 있게 함
- 스키마에서 필요없는 description 삭제 및 정리
> # EDIT - modified messages between mergers

- src/chain/types.hpp
- src/services/message_proxy.cpp
- src/services/message_validator.hpp
- tests/services/test.cpp
- 각 메시지에 대한 JSON Entry 검사
- ID, Signer Nonce, Diffie Hellman, TX ID의 경우 길이가 정해져 있으므로
enum class로 생성 후 길이가 동일하면 true
- Type은 CERTIFICATES / DIGESTS 가 맞다면 true
- Signer Count는 0 < signer_count <= config::MAX_SIGNER_NUM(200)면 true
- Height는 height == -1 || height > 0면 true
- Time은
1. MSG_JOIN은 시간차(현재시간-["time"])가 config::JOIN_TIMEOUT_SEC(10초)면 true
2. 나머지 MSG는 시간차(현재시간-["time"])가 config::MAX_WAIT_TIME(5초)면 true
- 실패하는 테스트 케이스 추가
>  # ADD - Message Validator 추가

- CMakeLists.txt
- include/easy_logging.cpp
- include/easy_logging.hpp
- main.cpp
- src/application.cpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/bootstraper/boot_straper.hpp
- src/modules/bp_scheduler/bp_scheduler.cpp
- src/modules/communication/grpc_util.cpp
- src/modules/communication/http_client.cpp
- src/modules/communication/http_client.hpp
- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- src/modules/message_fetcher/message_fetcher.cpp
- src/modules/message_fetcher/out_message_fetcher.cpp
- src/services/argv_parser.hpp
- src/services/block_generator.cpp
- src/services/block_generator.hpp
- src/services/block_processor.cpp
- src/services/block_validator.hpp
- src/services/message_proxy.cpp
- src/services/setting.hpp
- src/services/signature_requester.cpp
- src/services/signer_pool.cpp
- src/services/signer_pool_manager.cpp
- src/services/storage.cpp
- src/services/transaction_collector.cpp
- easy logging 라이브러리를 이용한 로그 시스템
- include 디렉토리에 cpp를 넣으면 발생하는 undefined 오류 방지를 위한 cmake 편집
1. include "easy_logging.hpp"
2. el::Loggers::getLogger("TAG"); 선언 - 글로벌로 선언하려면 리턴 값을 받아야 하므로, 각 클래스의 생성자에 넣어둡니다. 선언하지 않고 써도 되는데, 최초 호출 될때 DEBUG 메시지가 뜹니다.
3. CLOG(INFO,"TAG") 를 이용 - INFO, DEBUG, FATAL 등이 있으며 DEBUG는 지나치게 자세한 내용이 출력됩니다.
4. 로그 메시지를 끄려면 easy_logging.hpp를 편집
5. 태그는 3~4자리 영문 이용
- 컴파일할 때 도저히 이유를 알 수 없이, undefined 오류가 나면, include 나 src 디렉토리에서 마우스 우클릭후 Mark Directory as 메뉴에서 Project Sources and Headers 로 마크한 뒤 컴파일 하세요. cmake가 정상이어도, CLion이 다르게 파일을 인식해서 cpp 파일을 컴파일 하지 않아서 발생하는 오류입니다.
> # ADD - added easy logging library and edited log messages

- src/services/block_generator.cpp
- src/services/message_validator.hpp
- src/services/storage.cpp
1. Storage
- Block ID(JSON)의 type error
- .get<'string'>()이 빠져서 추가함
2. Block Generator
- 블록헤더의 해시의 type error
- 해시는 raw 데이터 형태인데 그대로 저장하다보니 invalid UTF-8 문제 발생
- raw데이터를 base64로 변환하여 저장
3. Message Validator
- Content validate 오류
- CERTIFICATES만 체크하고 있어서 DIGESTS일 때 문제가 발생함
- content의 원소들이 string인지만 체크
> # FIX - Storage, Block Generator, Message Validator 오류 수정

- include/concurrentqueue.hpp
- src/chain/merkle_tree.hpp
- src/chain/transaction.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/bootstraper/boot_straper.hpp
- src/modules/bp_scheduler/bp_scheduler.cpp
- src/modules/communication/connection_list.hpp
- src/modules/communication/message_handler.cpp
- src/modules/communication/rpc_receiver_list.hpp
- src/services/argv_parser.hpp
- src/services/block_generator.cpp
- src/services/block_processor.cpp
- src/services/block_validator.hpp
- src/services/input_queue.hpp
- src/services/message_factory.hpp
- src/services/message_validator.hpp
- src/services/signature_requester.cpp
- src/services/signer_pool_manager.cpp
- src/services/storage.cpp
- src/services/transaction_generator.cpp
- src/services/transaction_pool.cpp
- src/services/transaction_pool.hpp
- src/utils/random_number_generator.hpp
- src/utils/safe.hpp
- src/utils/type_converter.hpp
- tests/services/block_json.hpp
- tests/services/test.cpp
- tests/utils/test.cpp
- BlockGenerator에서 prev_block_id_b64에 raw 데이터를 넣었던 버그 수정
- MSG_TX 메시지 확인에 content 필드 확인 버그 수정
- 중복 TX 방법 수정
- InputQueueAlt에 concurrentqueue 적용
- toBase64Str을 encodeBase64로 바꿈
- json::parse를 Safe::parseJson에서 하도록 수정 (try-catch 관리 차원)
- 현재 tx_generator가 중복 TXID를 생성하므로, 테스트하기 위해서는 TXID 생성에 현재 시간 등을 넣어주어야 합니다.
- 로컬에서 생성한 TX 처리는 역시나 기가 막히게 잘 됩니다. (흠)
> # EDIT - fixed bugs, added concurrentqueue, edited duplicated TX check, and so on

- src/modules/communication/merger_client.cpp
- src/modules/communication/merger_client.hpp
- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- Rpc Channel을 열어 state를 통해 Server의 상태를 확인하려 했으나
server의 상태와 관계없이 status가 IDLE이 나타남. 따라서 Server의 상태에 관계없이 connection list 에서 true값을 setting 함.
- 기존에 사용하려고 했던 Rpc Health check protocol 사용하도록함
- 이전에 몇가지를 세팅하지 않아 default health check가 동작하지 않았던
문제 해결 하였음
- Merger 2개를 실행하였을때, 연결 되지 않았을때는 "NoWhere to send
message" log가 나오고, 연결 되었을시 해당 주소의 log가 나오는걸
확인. 또한 도중에 하나가 연결이 끊겼을시 다른 곳에서는 다시 NoWhere to
send message"가 나오는 것을 확인 하였음.
>  # EDIT - Rpc Health check 수정

- src/chain/types.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/communication/merger_client.cpp
- src/modules/communication/msg_schema.hpp
- src/services/signer_pool_manager.cpp
- REQ_CHECK의 json schema 추가
- MSG_LEAVE, MSG_ECHO에 대해서 json schema 확인을 할 필요가
없어져 삭제 (LEAVE의 경우 Internal msg , ECHO는 더 이상 사용하지 않음)
- MergerClient에서 checkSEMsgType()에서 RES_CHECK를
확인하고 SE로 메시지를 보내도록함.
>  # EDIT - Network에서 MSG_REQ_CHECK MSG_RES_CHECK 처리

- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- Rpc Server에서 예외가 발생해서 Server가 깨졌을때 completion queue에
쌓여있는 Rpc 객체들의 메모리를 해제 후 Rpc Server를 다시 시작하도록 함.
- Rpc 객체들의 proceed() parameter에  false를 넣을 시 해당주소의  메모리를 해제하도록 함.
- Merger 2개 , Signer 연결을 확인 하였습니다. Rpc Server에서 예외가 발생하는 것은 확인하지 못하였습니다.
>  # FIX - Rpc Server 예외 처리

- src/services/signature_requester.cpp
- 서명 가능한 signer 의 숫자를 비교하는 부분이 MIN값과 같을때도 드랍
해버림.
- MIN값과 같을때도 확인하도록 수정
>  # FIX - 가능한 SIgner의 숫자 체크하는 부분 수정

- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/bootstraper/bootstrapper.cpp
- 부트스트래핑 중 내가 가진 최신 블록과 동일한 블록이 도착했을 때, 멈추는 버그
- 네트워크가 상태가 좋지 않으면 중간에 블록을 잃어 버릴 수 도 있음
- 이 패치가 적용되면 동시에 머저를 켰을 때 멈추지 않음 (근본적인 해결책은 아님)
> # FIX - bug of hangup in bootstrap-blocksync

- src/chain/message.hpp
- src/config/config.hpp
- src/modules/communication/grpc_util.cpp
- src/modules/communication/grpc_util.hpp
- src/modules/communication/message_handler.cpp
- Msg header관련 상수 config/config.hpp -> chain/message.hpp 이동
- 이동에 따른 관련 코드 수정
- message.hpp에서 Message structure를 더 이상 사용하지 않으므로 삭제
- 일반 배열을 사용 했었던 부분 std::array로 변경
> # REFACTOR - Message Header 관련 상수 위치 수정

- src/chain/block.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/bp_scheduler/bp_scheduler.cpp
- src/services/argv_parser.hpp
- src/services/block_generator.hpp
- src/services/setting.hpp
- src/services/storage.cpp
- Bp scheduler에서 signer pool에서 'GOOD' status signer숫자만 보도록함
- Storage에서 readBlock()에서 값을 제대로 못 읽는 문제 해결
- 생성된 블록을 보낼 때, ssig 숫자 log 찍도록 함.
>  # FIX - bp scheduler 및 storage 수정

- src/modules/communication/http_client.cpp
- post로 데이터를 전송할때 escape하지 않고 전송하게 되면
`i6A0XxDmwYKfYoudEu/pZ5tu2+mChFu/+75OpWsrCfk=` -> `i6A0XxDmwYKfYoudEu/pZ5tu2 mChFu/ 75OpWsrCfk=`  '+' character가 blank space로 치환되는 문제가 생김
- 전송할때 데이터필드 escape하도록 수정
참조: https://stackoverflow.com/questions/5628738/strange-base64-encode-decode-problem
> # FIX - POST의 필드를 escape하지 않을때 발생하는 문제

- src/chain/join_temporary_data.hpp
- src/modules/communication/merger_client.cpp
- src/modules/communication/merger_server.cpp
- src/modules/communication/merger_server.hpp
- src/modules/communication/protos/protobuf_signer.grpc.pb.cc
- src/modules/communication/protos/protobuf_signer.grpc.pb.h
- src/modules/communication/protos/protobuf_signer.pb.cc
- src/modules/communication/protos/protobuf_signer.pb.h
- src/modules/communication/protos/protobuf_signer.proto
- src/modules/communication/rpc_receiver_list.hpp
- src/services/signer_pool_manager.cpp
- Signer / Merger protobuf 수정
- Signer로 메시지 보내는 부분 수정
- RpcReceiverList에서 stream rpc 정보 하나만 관리하도록 함.
- MergerServer에서 signer rpc에서 필요치 않은 코드 삭제
- Merger 2개 연결 확인
- Signer 연결 확인
- 블록 생성 후 저장 확인
> # REFACTOR - Signer / Merger rpc 수정

- src/modules/health_checker/block_health_checker.cpp
- endCheck 이후에 return이 없는 버그 (블록에 이상이 있을 때  segmentation fault가 뜰 수 있음)
> # FIX - fixed bug that is no return after endCheck()

- src/modules/block_processor/block_processor.cpp
- unresolved block pool을 작업하면서 빠졌던 중복 TX 삭제 기능 추가
- 시뮬레이터에서는 사실상 중복 TX를 생성하지 않으며, 2개 이상의 머저에서 테스트해야 되서...
> # FIX - added missing code to remove duplicated TX in block prorcessor

- src/chain/mem_ledger.hpp
- src/chain/types.hpp
- src/ledger/certificate_ledger.hpp
- src/modules/block_processor/block_processor.cpp
- src/modules/block_processor/block_processor.hpp
- src/modules/block_processor/unresolved_block_pool.hpp
- src/modules/bootstraper/block_synchronizer.cpp
- src/modules/communication/merger_client.cpp
- src/services/message_proxy.cpp
- src/services/storage.cpp
- src/services/storage.hpp
- MSG_REQ_STATUS / MSG_RES_STATUS 구현
- 순서에 맞지 않게 도착한 블록에서 파생된 ledger 정보 처리
- 블록 싱크가 block processor를 이용하도록 수정
- 블록 생성, 블록 싱크 동작
- 현재) A 머저가 7개 블록이 있을 때, B 머저는 5개까지만 저장하고, 2개는 unresolved block pool에 존재 (정상! A가 계속 블록을 생성하면 최종적으로 A와 B의 상태가 동일해짐.)
- getUnresolvedLowestLink를 캐시를 이용하도록 수정할 것. (코스트가 크지만 지속적으로 호출됨, 블록이 push 되었을때만 결과가 변동이 있음)
- MSG_REQ_BLOCK을 일정 시간 내에서는 한 번만 보내도록
> #EDIT - MSG_REQ_STATUS / MSG_RES_STATUS
